dim: clean up dim checkpatch output
Use a local var for the commit for clarity. Print oneline commit summary
before the output. Use checkpatch.pl -q option to reduce output. Reduce
newlines printed for errors and warnings. Return 1 instead of exit 1 on
errors so we can continue as needed.

All of this is to better support other uses for dim_checkpatch in follow
up work.

diff --git a/dim b/dim
--- a/dim
+++ b/dim
@@ -284,16 +284,19 @@ function check_repo_clean
 # $1 is the git sha1 to check
 function dim_checkpatch
 {
-	git show $1 --pretty=email | scripts/checkpatch.pl --strict - || true
-	if git show $1 | grep '^\+.*\WBUG' > /dev/null; then
+	local commit=$1
+
+	git --no-pager log --oneline -1 $commit
+	git show $commit --pretty=email | scripts/checkpatch.pl -q --strict - || true
+	if git show $commit | grep '^\+.*\WBUG' > /dev/null; then
 		if [[ $FORCE ]] ; then
-			echo -e "\n\nWARNING: New BUG macro added\n"
+			echo "WARNING: New BUG macro added"
 		else
-			echo -e "\n\nERROR: New BUG macro added\n"
-			exit 1
+			echo "ERROR: New BUG macro added"
+			return 1
 		fi
 	fi
-	git show $1 | grep '^\+.*drm_i915_private_t' > /dev/null && echo -e "\n\nWARNING: New drm_i915_private_t added\n" || true
+	git show $commit | grep '^\+.*drm_i915_private_t' > /dev/null && echo "WARNING: New drm_i915_private_t added" || true
 }
 
 function prep_pull_mail_tags
