dim: add command to check for dim updates
Add a command to check if the user is running an up-to-date version of
dim.

Acked-by: Daniel Vetter <daniel@ffwll.ch>
Signed-off-by: Jani Nikula <jani.nikula@intel.com>

diff --git a/dim b/dim
--- a/dim
+++ b/dim
@@ -179,6 +179,27 @@ if [ "$subcommand" != "setup" -a "$subcommand" != "help" -a "$subcommand" != "us
 		xargs -n 1 echo | grep '^origin' | sed -e 's/^origin\///'`
 fi
 
+function dim_uptodate
+{
+	local using="${BASH_SOURCE[0]}"
+
+	if [[ ! -e "$using" ]]; then
+		echo "$dim: could not figure out the version being used ($using)." >&2
+		exit 1
+	fi
+
+	if [[ ! -e "$DIM_PREFIX/maintainer-tools/.git" ]]; then
+		echo "$dim: could not find the upstream repo for $dim." >&2
+		exit 1
+	fi
+
+	if ! git --git-dir=$DIM_PREFIX/maintainer-tools/.git show origin/maintainer-tools:dim |\
+			diff "$using" - >& /dev/null; then
+		echo "$dim: not running upstream version of the script." >&2
+		exit 1
+	fi
+}
+
 # get message id from file
 # $1 = file
 message_get_id ()
