dim: Reject patches that add new BUG_ON
Except when -f is set to override this. I've wasted enough time
chasing hard-hangs due to over-eager usage of BUG_ONs.

diff --git a/dim b/dim
--- a/dim
+++ b/dim
@@ -280,7 +280,14 @@ function check_repo_clean
 function dim_checkpatch
 {
 	git show $1 --pretty=email | scripts/checkpatch.pl --strict - || true
-	git show $1 | grep '^\+.*\WBUG' > /dev/null && echo -e "\n\nWARNING: New BUG macro added\n" || true
+	if git show $1 | grep '^\+.*\WBUG' > /dev/null; then
+		if [[ $FORCE ]] ; then
+			echo -e "\n\nWARNING: New BUG macro added\n"
+		else
+			echo -e "\n\nERROR: New BUG macro added\n"
+			exit 1
+		fi
+	fi
 	git show $1 | grep '^\+.*drm_i915_private_t' > /dev/null && echo -e "\n\nWARNING: New drm_i915_private_t added\n" || true
 }
 
